# Generated by Django 4.1.4 on 2022-12-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("keywords", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("detail", models.TextField()),
                ("price", models.FloatField()),
                ("months", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("True", "Evet"), ("False", "Hayir")],
                        max_length=10,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("uptade_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
