# Generated by Django 4.1.4 on 2022-12-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_job_category_id_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=5, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
