# Generated by Django 4.1.4 on 2022-12-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_remove_category_parent_alter_job_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="category_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="job.category",
            ),
        ),
    ]
