# Generated by Django 4.1.4 on 2022-12-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_alter_job_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
