# Generated by Django 4.1.4 on 2022-12-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_alter_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
