# Generated by Django 4.1.4 on 2022-12-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0008_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
