# Generated by Django 4.1.4 on 2022-12-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0009_alter_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="job.tag"),
        ),
    ]
