# Generated by Django 4.1.4 on 2022-12-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0010_job_tags"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="tags",),
        migrations.DeleteModel(name="Tag",),
    ]
